### PR TITLE
Design ta3 for segment editing

### PR DESCRIPTION
**Pull request by dimitri-yatsenko**

### CODE REVIEW

**Review by amwilson149 — APPROVED** [review]
We should discuss how to assign a precursor ID in the case of a merger (in which case at least 2 IDs turn into 1 new one, and it's not clear why one ID would be more important to store than another).

Also, in a future iteration, the Segment label needs to be broken up into different lookups (or some equivalent change needs to be made). Currently, a segment can be identified by more than one of the labels in the contents list (e.g. a segment could be both "sparsely spiny" and "Martinotti"). Each new lookup should have a list of mutually exclusive options.

**Comment by dimitri-yatsenko** [comment]
@amwilson149 , The current design for Precursor allows both merges and splits.  Both the segment id and its precursor id are in the primary key.  This means that you can have many entries with the same precursor and many entries with the same segment.

**Comment by amwilson149** [comment]
@dimitri-yatsenko so if we merged 4 segments into one new segment, we would have 4 tuples in this table, each one with a different precursor?

**Comment by dimitri-yatsenko** [comment]
@amwilson149 yes

**Comment by dimitri-yatsenko** [comment]
@amwilson149 Yes, and the precursors would be entered into the `Retired` table to indicate that they are no longer used.

**Comment by amwilson149** [comment]
@dimitri-yatsenko okay. As long as this strategy won't be too much of a memory sink then I have no issue with it.

**Comment by dimitri-yatsenko** [comment]
@amwilson149 No, this is a rather standard approach to implement a graph.  If we get to billions of splits and merges, we will have slow performance on some operations and we will find ways to speed it up.

**Comment by amwilson149** [comment]
@dimitri-yatsenko we should start assessing whether we will get to the point of billions of splits/merges. My impression is that we might.  So it might be important to think about performance in order to have a useable schema for Pinky100.  I have started a parallel discussion on Slack.

**Pull request merged**
